---
include:
  - board: eyelash_sofle_right
    shield: nice_view
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: eyelash_sofle_left
  - board: nice_nano_v2
    shield: settings_reset
